# Generated by Django 3.1.4 on 2020-12-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_course_pricing_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='currency',
            field=models.CharField(default='usd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=17.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='stripe_price_id',
            field=models.CharField(default='django-free-trial', max_length=50),
            preserve_default=False,
        ),
    ]
